/**
 * Canonical publishing error codes aligned with PUBLISHING_AUTOMATION_ARCHITECTURE.md §12.
 * Every controller and service must throw only these codes — never raw library errors.
 */
export const PublishingErrorCode = {
  CONTRACT_UNSUPPORTED: "PUBLISHING_CONTRACT_UNSUPPORTED",
  CANDIDATE_INVALID: "PUBLISHING_CANDIDATE_INVALID",
  CANDIDATE_TAMPERED: "PUBLISHING_CANDIDATE_TAMPERED",
  CANDIDATE_REVOKED: "PUBLISHING_CANDIDATE_REVOKED",
  TARGET_NOT_CONNECTED: "PUBLISHING_TARGET_NOT_CONNECTED",
  TARGET_UNAUTHORIZED: "PUBLISHING_TARGET_UNAUTHORIZED",
  FORMAT_UNSUPPORTED: "PUBLISHING_FORMAT_UNSUPPORTED",
  ASSET_UNAVAILABLE: "PUBLISHING_ASSET_UNAVAILABLE",
  ASSET_TAMPERED: "PUBLISHING_ASSET_TAMPERED",
  SCHEDULE_IN_PAST: "PUBLISHING_SCHEDULE_IN_PAST",
  APPROVAL_REQUIRED: "PUBLISHING_APPROVAL_REQUIRED",
  STATE_CONFLICT: "PUBLISHING_STATE_CONFLICT",
  IDEMPOTENCY_CONFLICT: "PUBLISHING_IDEMPOTENCY_CONFLICT",
  DUPLICATE_DISPATCH: "PUBLISHING_DUPLICATE_DISPATCH",
  WEBHOOK_UNAUTHORIZED: "PUBLISHING_WEBHOOK_UNAUTHORIZED",
  WEBHOOK_TIMESTAMP_INVALID: "PUBLISHING_WEBHOOK_TIMESTAMP_INVALID",
  WEBHOOK_NONCE_REPLAYED: "PUBLISHING_WEBHOOK_NONCE_REPLAYED",
  PROVIDER_RATE_LIMITED: "PUBLISHING_PROVIDER_RATE_LIMITED",
  PROVIDER_FAILURE: "PUBLISHING_PROVIDER_FAILURE",
  PROVIDER_OUTCOME_UNKNOWN: "PUBLISHING_PROVIDER_OUTCOME_UNKNOWN",
  CALLBACK_INVALID: "PUBLISHING_CALLBACK_INVALID",
  CALLBACK_CONFLICT: "PUBLISHING_CALLBACK_CONFLICT",
  INVALID_TIMEZONE: "PUBLISHING_INVALID_TIMEZONE",
  INVALID_SCHEDULE: "PUBLISHING_INVALID_SCHEDULE",
  VERSION_CONFLICT: "PUBLISHING_VERSION_CONFLICT",
  NOT_FOUND: "PUBLISHING_NOT_FOUND",
  FORBIDDEN: "PUBLISHING_FORBIDDEN",
  FORBIDDEN_NO_BUSINESS: "PUBLISHING_FORBIDDEN_NO_BUSINESS",
} as const;

export type PublishingErrorCodeValue =
  (typeof PublishingErrorCode)[keyof typeof PublishingErrorCode];
