-- Auto-generated drift reconciliation (issue #123).
--
-- Generated by `prisma migrate dev --create-only` when the publishing-export
-- manifest column was added: the committed schema had already removed the
-- `updated_at` DEFAULT from publication_candidate_outbox and prisma's
-- shadow-DB diff surfaced pre-existing index-name/constraint churn on the
-- billing tables. Nothing here changes behaviour — it aligns the replay of
-- the earlier migrations with the schema. Do not delete: `prisma migrate
-- status` reports the database out of sync without it.
-- DropForeignKey
ALTER TABLE "billing_checkout_attempts" DROP CONSTRAINT "billing_checkout_attempts_price_id_fkey";

-- DropForeignKey
ALTER TABLE "billing_subscriptions" DROP CONSTRAINT "billing_subscriptions_price_id_fkey";

-- AlterTable
ALTER TABLE "publication_candidate_outbox" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AddForeignKey
ALTER TABLE "billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_price_id_fkey" FOREIGN KEY ("price_id") REFERENCES "billing_prices"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billing_checkout_attempts" ADD CONSTRAINT "billing_checkout_attempts_price_id_fkey" FOREIGN KEY ("price_id") REFERENCES "billing_prices"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "billing_checkout_attempts_billing_account_id_idempotency_key_ke" RENAME TO "billing_checkout_attempts_billing_account_id_idempotency_ke_key";

-- RenameIndex
ALTER INDEX "billing_payment_transactions_provider_provider_transaction_id_k" RENAME TO "billing_payment_transactions_provider_provider_transaction__key";

-- RenameIndex
ALTER INDEX "billing_provider_cost_ledger_billing_account_id_billing_period_" RENAME TO "billing_provider_cost_ledger_billing_account_id_billing_per_idx";

-- RenameIndex
ALTER INDEX "billing_provider_cost_ledger_billing_account_id_logical_artifac" RENAME TO "billing_provider_cost_ledger_billing_account_id_logical_art_key";

-- RenameIndex
ALTER INDEX "billing_usage_ledger_billing_account_id_metric_period_start_cla" RENAME TO "billing_usage_ledger_billing_account_id_metric_period_start_key";

-- RenameIndex
ALTER INDEX "billing_usage_ledger_billing_account_id_metric_period_start_per" RENAME TO "billing_usage_ledger_billing_account_id_metric_period_start_idx";
