import type {
  ContentCaptionVariant,
  ContentItemVersion,
} from "../content-item";
import type { IsoDateTime, UUID } from "../content-types";
import type { ContentV2EditKind } from "./content-v2-types";

/**
 * Immutable item-version edit metadata (content-v2, issue #187).
 *
 * Every persisted v2 item version records how it was produced: generated by
 * the worker, a direct owner edit, or an AI-assisted rewrite. Direct edits
 * and rewrites always carry the base version id and checksum that the owner
 * saw; stale base versions surface a conflict instead of overwriting
 * content. Persisted versions are always validated.
 */
export type ContentVersionEditMetadataV2 = {
  readonly edit_kind: ContentV2EditKind;
  /** Null for worker-generated first versions. */
  readonly base_version_id: UUID | null;
  /** Checksum of the base version; optimistic-concurrency gate. */
  readonly base_version_checksum: string | null;
  /** Owning user for direct edits; null for worker/AI-produced versions. */
  readonly edited_by_user_id: UUID | null;
  /** Persisted versions pass deterministic validation before creation. */
  readonly validation_state: "validated";
  readonly edited_at: IsoDateTime;
};

/**
 * The content-v2 item version keeps the v1 version surface (readable by the
 * same review surfaces) and adds immutable edit metadata. The frozen v1
 * `ContentItemVersion` type itself is never modified.
 */
export type ContentItemVersionV2 = Omit<
  ContentItemVersion,
  "contract_version" | "strategy_trace"
> & {
  readonly contract_version: "content-v2";
  readonly edit_metadata: ContentVersionEditMetadataV2;
};

/**
 * Direct owner edit request. The API creates a new immutable version only
 * when `base_version_id` + `base_version_checksum` match the current
 * version; otherwise it fails with `CONTENT_VERSION_CONFLICT`.
 */
export type OwnerContentDirectEditRequest = {
  readonly contract_version: "content-v2";
  readonly content_item_id: UUID;
  readonly base_version_id: UUID;
  readonly base_version_checksum: string;
  readonly caption_variants: readonly ContentCaptionVariant[];
  readonly cta: string | null;
  readonly hashtags: readonly string[];
  readonly alt_text: string;
  readonly creative_brief: string;
  readonly idempotency_key: string;
};

export type OwnerContentDirectEditResponse = {
  readonly contract_version: "content-v2";
  readonly item_version: ContentItemVersionV2;
};
