export const ERROR_CODES = {
  DISCOVERY_SESSION_NOT_FOUND: "DISCOVERY_SESSION_NOT_FOUND",
  DISCOVERY_SESSION_STATE_CONFLICT: "DISCOVERY_SESSION_STATE_CONFLICT",
  DISCOVERY_RESEARCH_CAP_EXCEEDED: "DISCOVERY_RESEARCH_CAP_EXCEEDED",
  DISCOVERY_AI_SERVICE_UNAVAILABLE: "DISCOVERY_AI_SERVICE_UNAVAILABLE",
  DISCOVERY_AI_BAD_RESPONSE: "DISCOVERY_AI_BAD_RESPONSE",
  DISCOVERY_PROFILE_ALREADY_CONFIRMED: "DISCOVERY_PROFILE_ALREADY_CONFIRMED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACTION_TOKEN_INVALID: "ACTION_TOKEN_INVALID",
  ACTION_TOKEN_CONSUMED: "ACTION_TOKEN_CONSUMED",
  ACTION_TOKEN_EXPIRED: "ACTION_TOKEN_EXPIRED",
  AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",
  FEDERATED_IDENTITY_CONFLICT: "FEDERATED_IDENTITY_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
